### ISSUE TITLE
invalid component definition, can't find component [test.DS_Store]

### ISSUE THREAD

**Issue by neokoenig** [robinhilliard/rocketunit#1]
There should be the equivalent of gitignore to mask mac's annoying DS_Store files; as it is, if you have a `.DS_Store` file in `/tests` you get `invalid component definition, can't find component [test.DS_Store]`

**Comment by robinhilliard** [comment]
Hi, thanks for pointing this out, I've added a filter to the directory tag to ignore non cfc files, does this address your problem?

**Comment by neokoenig** [comment]
Ah yes, that's a much better solution - cheers!
